### PR TITLE
Automatically embed YouTube videos from posted links

### PR DESCRIPTION
**Pull request by ozziash**

### CODE REVIEW

**Comment by ozziash** [comment]
Hello @elektronaut , I made this pull request more than two weeks ago and I noticed that you replied on the one posted more recently. Is there something wrong with my pull request? Thanks

**Comment by elektronaut** [comment]
Hey! Thanks and sorry! I've got lots on my plate right now, and haven't had a chance to look properly at it yet.

The button is a great addition, especially on mobile where getting a YouTube embed code is a pain. 

I'm not so sure about adding custom syntax to Markdown, especially since Markdown handles inline HTML just fine. I'm not opposed to it, just not sure if it's necessary. I doubt anyone will be typing in YouTube IDs manually.

Another issue is that this loses the size information from the YouTube embed, so there's no way to know what aspect ratio a video is.

**Comment by ozziash** [comment]
Thanks for the comments. I actually like the markdown solution better, because it may be unnecessary to burden MDown with HTML code when you can write a macro for it (which is inserted using the button).

As for the aspect of the video, information about the size can be found in the generated embed code from Youtube. Which would require another input from user and thus wouldn't be very automatic since all user should provide is the link itself. I found a possible <a href="http://fettblog.eu/blog/2013/06/16/preserving-aspect-ratio-for-embedded-iframes/" target="_blank">solution</a> using CSS. If you'll be ok with the markdown solution, I can implement it right away.

**Comment by elektronaut** [comment]
Thanks. I merged it in, I can take care of the CSS if it causes any trouble.

**Pull request merged**
